// hw6-angular/src/app/components/register/register.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { Restangular } from 'ngx-restangular';

@Component({
  selector: 'app-register',
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.css']
})
export class RegisterComponent {
  username = 'user';
  password = 'pass';

  constructor(
    private router: Router,
    private restangular: Restangular,
  ) { }

  submit() {
    console.log('submitting');
    console.log('this.username:',this.username);
    console.log('this.password:',this.password);

    const login = this.restangular.all('user');

    login.post({
      username: this.username,
      password: this.password
    })
    .toPromise()
    .then((res) => {
      console.log(`created:`);
      console.log(res);
      this.router.navigate(['/login']);
    })
    .catch((err) => {
      console.error(err);
    });
  }


}

<header class="header">
  <a routerLink="/chat"><img src="assets/angie-chat.svg" alt="" /></a>
  <nav class="nav">
    <a routerLink="/chat" routerLinkActive="active">Chat</a>
    <a routerLink="/login" routerLinkActive="active">Login</a>
    <a routerLink="/register" routerLinkActive="active">Register</a>
  </nav>
</header>
<div>
  <div>
    <form class="register__form" (submit)="submit()" autoComplete="off">
      <div class="register__block"> Username:
        <input
          class="register__input"
          type="text"
          name="username"
          [(ngModel)]="username" />
      </div>
      <div class="register__block"> Password:
        <input
          class="register__input"
          type="password"
          name="password"
          [(ngModel)]="password" />
      </div>
      <div class="register__block"> Confirm Password:
        <input
          class="register__input"
          type="password"
          name="password2"
          [(ngModel)]="password2" />
      </div>
      <button
        type="submit"
        id="equal"
        class="register__button .register__button-submit"> Register </button>
    </form>
    <a routerLink="/login" class="register__link">
      Already registered? Log in!
    </a>
  </div>
</div>

// hw10-fabric/src/components/Register.jsx
import React from 'react';
import PropTypes from 'prop-types';
import { Link } from 'react-router-dom';
import axios from 'axios';
import uriPrefix from './uriPrefix';

class Login extends React.Component {
  constructor(props) {
    super(props);

    this.state = {
      username: '',
      password: '',
      password2: '',
    };

    this.submit = this.submit.bind(this);
  }

  render() {
    return (
      <div>
        <h1>Register</h1>
        <div>
          <form className="login__form" onSubmit={this.submit} autoComplete="off">
            <div className="login__block"> Username:
              <input
                className="login__input"
                type="text"
                value={this.state.username}
                onChange={e => this.setState({ username: e.target.value })} />
            </div>
            <div className="login__block"> Password:
              <input
                className="login__input"
                type="password"
                value={this.state.password}
                onChange={e => this.setState({ password: e.target.value })} />
            </div>
            <div className="login__block"> Confirm Password:
              <input
                className="login__input"
                type="password"
                value={this.state.password2}
                onChange={e => this.setState({ password2: e.target.value })} />
            </div>
            <button
              type="submit"
              id="equal"
              className="login__button login__button-submit"> Register </button>
          </form>
          <Link to="/login" className="login__link">
            Already registered? Log in! </Link>
        </div>
      </div>
    );
  }

  submit(e) {   // eslint-disable-line
    console.log('submitting');   // eslint-disable-line
    e.preventDefault();

    axios.post(`${uriPrefix}/api/user`, {
      username: this.state.username,
      password: this.state.password
    })
    .then((res) => {
      console.log(`created:`);   // eslint-disable-line
      console.log(res);   // eslint-disable-line
      this.props.history.push('/login');
    })
    .catch((err) => {
      console.log(err); // eslint-disable-line
    });
  }
}

Login.propTypes = {
  input: PropTypes.string,
  history: PropTypes.object.isRequired,
};

export default Login;
