// hw6-angular/src/app/components/login/login.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { Restangular } from 'ngx-restangular';

import { AuthService } from '../../services/auth.service';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent {
  username = 'user';
  password = 'pass';

  constructor(
    private router: Router,
    private restangular: Restangular,
    private authService: AuthService,
  ) {}

  submit() {
    console.log('submitting');
    console.log('this.username:',this.username);
    console.log('this.password:',this.password);

    const login = this.restangular.all('user/login');

    login.post({
      username: this.username,
      password: this.password
    })
    .toPromise()
    .then((res) => {
      console.log(res);
      this.authService.saveSession(res.token, this.username);
      this.router.navigate(['/']);
    })
    .catch((err) => {
      console.error(err);
    });
  }

}

<header class="header">
  <a routerLink="/chat"><img src="assets/angie-chat.svg" alt="" /></a>
  <nav class="nav">
    <a routerLink="/chat" routerLinkActive="active">Chat</a>
    <a routerLink="/login" routerLinkActive="active">Login</a>
    <a routerLink="/register" routerLinkActive="active">Register</a>
  </nav>
</header>
<div>
  <div>
    <form class="login__form" autoComplete="off">
      <div class="login__block"> Username:
        <input
          class="login__input"
          type="text"
          name="username"
          [(ngModel)]="username" />
      </div>
      <div class="login__block"> Password:
        <input
          class="login__input"
          type="password"
          name="password"
          [(ngModel)]="password" />
      </div>
      <button
        type="button"
        (click)="submit()"
        class="login__button login__button-submit"> Log in </button>
    </form>
  </div>
  <a routerLink="/register" class="login__link">
    Not yet registered? Register for free!
  </a>
</div>

// hw4-nodejs/src/components/Login.jsx
import React from 'react';
import PropTypes from 'prop-types';
import { Link } from 'react-router-dom';
import axios from 'axios';
import uriPrefix from './uriPrefix';

class Login extends React.Component {
  constructor(props) {
    super(props);

    this.state = {
      username: '',
      password: '',
    };

    this.submit = this.submit.bind(this);
  }

  render() {
    return (
      <div>
        <h1>Log in</h1>
        <div>
          <form className="login__form" onSubmit={this.submit} autoComplete="off">
            <div className="login__block"> Username:
              <input
                className="login__input"
                type="text"
                value={this.state.username}
                onChange={e => this.setState({ username: e.target.value })} />
            </div>
            <div className="login__block"> Password:
              <input
                className="login__input"
                type="password"
                value={this.state.password}
                onChange={e => this.setState({ password: e.target.value })} />
            </div>
            <button
              type="submit"
              className="login__button login__button-submit"> Log in </button>
          </form>
          <Link to="/register" className="login__link">
            Not yet registered? Register for free! </Link>
        </div>
      </div>
    );
  }

  submit(e) {   // eslint-disable-line
    console.log('submitting');   // eslint-disable-line
    e.preventDefault();

    axios.post(`${uriPrefix}/api/user/login`, {
      username: this.state.username,
      password: this.state.password
    })
    .then((res) => {
      sessionStorage.setItem('token', res.data.token);  // eslint-disable-line
      sessionStorage.setItem('username', this.state.username);  // eslint-disable-line
      this.props.history.push('/');
    })
    .catch((err) => {
      console.log(err); // eslint-disable-line
    });
  }
}

Login.propTypes = {
  input: PropTypes.string,
  history: PropTypes.object.isRequired,
};

export default Login;
